services:

  SBublies\Gridtocontainer\Command\MigrateAllCommand:
    tags:
      - name: 'console.command'
        command: 'gridtocontainer:migrateall'
        description: 'Migrate all from grid identifier e.g. ce_columns2'
        schedulable: false

  SBublies\Gridtocontainer\Command\LogColPosErrorsCommand:
    tags:
      - name: 'console.command'
        command: 'gridtocontainer:logcolposerrors'
        description: 'Update content'
        schedulable: false

  SBublies\Gridtocontainer\Command\FixColPosErrorsCommand:
    tags:
      - name: 'console.command'
        command: 'gridtocontainer:fixcolposerrors'
        description: 'Update content'
        schedulable: false
