services:

  SBublies\Gridtocontainer\Command\MigrateAllCommand:
    tags:
      - name: 'console.command'
        command: 'gridtocontainer:migrateall'
        description: 'Migrate all from grid identifier e.g. ce_columns2'
        schedulable: false

  SBublies\Gridtocontainer\Command\UpdateContentCommand:
    tags:
      - name: 'console.command'
        command: 'gridtocontainer:updatecontent'
        description: 'Update content'
        schedulable: false
